### ISSUE TITLE
[FEAT] 좋아요, 스크랩 기능 구현

### ISSUE THREAD

**Issue by ckdmstn** [Hanium2023-WeB/starD-backend-refactoring#26]
### 💼 작업 설명
- 스크랩 - 스터디, 스터디 게시글
- 좋아요 - 커뮤니티

### ✅ To-do

- [x] 좋아요, 스크랩 추가 
- [x] 좋아요, 스크랩 삭제
- [x] 게시글 - 좋아요 개수 조회
- [x] 스터디 - 스크랩 개수 조회
- [x] 사용자 - 스크랩 한 게시글 조회

#### 논의사항
- 사용자가 좋아요 누른 게시글 리스트 조회 필요한지? -> 구현 완료
