### ISSUE TITLE
[FEAT] 프로필 사진 조회, 수정, 삭제 구현

### ISSUE THREAD

**Issue by yslle** [Hanium2023-WeB/starD-backend-refactoring#31]
### 💼 작업 설명

프로필 사진 조회, 수정, 삭제 기능 구현
### ✅ To-do

- [ ] 프로필 사진 조회
- [ ] 프로필 사진 수정 - 삭제 후 새로 생성
- [ ] 프로필 사진 삭제
