### ISSUE TITLE
[FEAT] 스터디 신청 관련 API 구현

### ISSUE THREAD

**Issue by rosieisor** [Hanium2023-WeB/starD-backend-refactoring#46]
### ✅ To-do

- [x] 스터디 신청 API 구현
- [x] 스터디 신청자 목록 조회 API 구현
- [x] 스터디 신청자 선택 API 구현
