### ISSUE TITLE
[FEAT] 프로필 관련 API 기능 구현

### ISSUE THREAD

**Issue by rosieisor** [Hanium2023-WeB/starD-backend-refactoring#56]
### ✅ To-do

- [ ] 프로필 조회 API 구현
- [x] 프로필 자기 소개 수정  API 구현
- [ ] _다른 사용자 프로필 조회 API 구현_
- [x] 개인 신뢰도 조회 API 구현

**Comment by ckdmstn** [comment]
신뢰도 부분 Dto로 전달할 때 
```
new BigDecimal(profile.getCredibility()).setScale(2, RoundingMode.HALF_UP).doubleValue()
```
이거만 추가 부탁드립니다! DB에 넣을 때 반올림해서 넣을까 했는데 신뢰도 계산 과정이 조금이라도 오차가 생기는 거보다는 화면에 보여질 때 반올림하는 게 나을 거 같아서요!
