### ISSUE TITLE
[FEAT] 스터디 관련 수정사항

### ISSUE THREAD

**Issue by rosieisor** [Hanium2023-WeB/starD-backend-refactoring#64]
### ✅ To-do

- [x] 스터디 검색 조건 @RequestBody 대신 @RequestParam 사용
- [x] 스터디 목록 조회 시, 스크랩 여부 필드 추가
- [x] 팀블로그 스터디원 목록 조회
