### ISSUE TITLE
[FEAT] 남은 기능 구현

### ISSUE THREAD

**Issue by rosieisor** [Hanium2023-WeB/starD-backend-refactoring#89]
### ✅ To-do

- [x] 토큰 만료 시간 확인 API 구현
- [x] 인기 스터디 분야 조회 API 구현
- [x] 자기소개 수정 API 구현
- [x] 스터디 중단 API 구현
